name: MessageEngine
version: '1.0'
main: org.mellurboo.messageEngine.MessageEngine
api-version: '1.21'
load: STARTUP
authors: [ Mellurboo ]
commands:
  messageEngine:
    description: message engine plugin controller
  me:
    description: message engine plugin controller
permissions:
  messageEngine.reload:
    default: false
